export type Fixture={home_code:string;away_code:string};
export type CpuResult=Fixture&{home_goals:number;away_goals:number;is_user_match:boolean};
export type Starter={player_id:string;player_name:string;role:string;confidence:number;managerTrust?:number|null;strength?:number|null;fitness?:number|null;penaltyTaker?:boolean;penaltyOrder?:number|null;setPieceTaker?:boolean;setPieceOrder?:number|null};
export type MatchEvent={minute:number;type:string;side:'user'|'opp';player?:Starter|null;assist?:Starter|null;desc:string;xg?:number;shotOnTarget?:boolean;x?:number;y?:number;energy?:number;injuryWeeks?:number;injuryLabel?:string;injuryCategory?:'muscular'|'traumatic';injurySeverity?:'minor'|'moderate'|'serious'|'major'};
export function seeded(seed:string){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>((h=Math.imul(h^(h>>>15),2246822519))>>>0)/4294967296}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));function poisson(lambda:number,rnd:()=>number){const L=Math.exp(-lambda);let p=1,k=0;do{k++;p*=Math.max(.000001,rnd())}while(p>L&&k<9);return clamp(k-1,0,6)}
export function confidenceFactor(c:number,trust=50){const conf=clamp((c-50)/50,-1,1)*.06,rel=clamp((trust-50)/50,-1,1)*.035;return 1+conf+rel}
export function clubStrength(rows:{team_nfl:string|null;fvm_fc:number|null;quotazione_fc:number|null}[]){const by:Record<string,number[]>={};for(const p of rows){if(!p.team_nfl)continue;(by[p.team_nfl]??=[]).push(Number(p.fvm_fc||p.quotazione_fc||1))}const out:Record<string,number>={};for(const [club,vals] of Object.entries(by)){vals.sort((a,b)=>b-a);const xi=vals.slice(0,11);out[club]=xi.length?xi.reduce((a,b)=>a+b,0)/xi.length:1}return out}
export function simulateCpuFixture(run:string,round:number,f:Fixture,strength:Record<string,number>):CpuResult{const rnd=seeded(`${run}|g${round}|${f.home_code}|${f.away_code}`),h=strength[f.home_code]||50,a=strength[f.away_code]||50,diff=clamp((h-a)/Math.max(30,(h+a)/2),-.45,.45);return{...f,home_goals:poisson(clamp(1.51+.55*diff,.45,2.35),rnd),away_goals:poisson(clamp(1.20-.55*diff,.35,2.2),rnd),is_user_match:false}}
function pick(rnd:()=>number,ps:Starter[],kind:'shot'|'creator'|'defender'){const rw:any=kind==='shot'?{P:.001,D:.22,C:.7,A:1.8}:kind==='creator'?{P:.03,D:.45,C:1.45,A:1.1}:{P:.1,D:1.7,C:1,A:.35};const w=ps.map(p=>(rw[p.role]||1)*confidenceFactor(p.confidence,p.managerTrust??50)*(0.72+Math.min(1.5,Number(p.strength||55)/75))),t=w.reduce((a,b)=>a+b,0);let x=rnd()*t;for(let i=0;i<ps.length;i++){x-=w[i];if(x<=0)return ps[i]}return ps[ps.length-1]}
export function buildMatchEvents(run:string,round:number,style:string,opp:string,ps:Starter[],oppPs:Starter[]=[],dryStreak=0,mentality:'attack'|'balanced'|'defend'='balanced'){
 const rnd=seeded(`${run}|g${round}|${style}|${mentality}|match9`),coordRnd=seeded(`${run}|g${round}|${style}|${mentality}|coords5`),out:MatchEvent[]=[];
 const avg=ps.reduce((a,p)=>a+Number(p.strength||55),0)/Math.max(1,ps.length),oppAvg=oppPs.reduce((a,p)=>a+Number(p.strength||55),0)/Math.max(1,oppPs.length||1),conf=ps.reduce((a,p)=>a+p.confidence,0)/Math.max(1,ps.length),trust=ps.reduce((a,p)=>a+Number(p.managerTrust??50),0)/Math.max(1,ps.length);
 const styleShare:any={Equilibrato:.50,Possesso:.55,Verticale:.51,Contropiede:.47,Pressing:.53},streakBoost=clamp(dryStreak*.045,0,.16),strengthEdge=oppPs.length?clamp((avg-oppAvg)/180,-.07,.07):0;
 const mentalityShare=mentality==='attack'?.055:mentality==='defend'?-.045:0,usShare=clamp((styleShare[style]||.5)+mentalityShare+strengthEdge+(conf-50)*.0007+(trust-50)*.00035,.36,.66);
 let usGoals=0,opGoals=0,m=2,injuryCount=0;const yellows=new Map<string,number>(),sentOffUser=new Set<string>(),sentOffOpp=new Set<string>(),fatigueNoted=new Set<string>();
 const add=(minute:number,type:string,side:'user'|'opp',player:Starter|null|undefined,desc:string,extra:any={})=>{const dir=side==='user'?1:-1,base=type==='goal'?94:type==='shot_saved'||type==='shot_missed'||type==='shot_attempt'?86:type==='press'?68:type==='transition'?64:type==='action'?70:type==='duel'?52:type==='possession'?35:type==='keeper_save'?8:50,x=extra.x??(dir===1?base:100-base),y=extra.y??(18+coordRnd()*64);out.push({minute:Math.min(89,minute),type,side,player:player||null,desc,x:+clamp(x,3,97).toFixed(1),y:+clamp(y,7,93).toFixed(1),...extra})};
 const activePool=(pool:Starter[],side:'user'|'opp')=>pool.filter(p=>!(side==='user'?sentOffUser:sentOffOpp).has(p.player_id));
 const liveEnergy=(p:Starter|null|undefined,minute:number)=>{if(!p)return 100;const base=Number(p.fitness??100),roleDrop=p.role==='A'?.15:p.role==='C'?.16:p.role==='D'?.13:.08,styleDrop=style==='Pressing'?.045:style==='Verticale'?.025:0,mentalityDrop=mentality==='attack'?.018:0;return clamp(base-minute*(roleDrop+styleDrop+mentalityDrop),38,100)};
 const maybeFatigue=(side:'user'|'opp',p:Starter|null|undefined,minute:number)=>{if(!p||minute<54||fatigueNoted.has(p.player_id))return;const energy=liveEnergy(p,minute),chance=energy<62?clamp(.22+(62-energy)*.045,.22,.72):clamp((70-energy)*.025,.04,.22);if(energy<70&&rnd()<chance){fatigueNoted.add(p.player_id);const desc=side==='user'&&energy<63?`VICE — ${p.player_name} è in riserva: ${Math.round(energy)}% di energia. Le corse stanno perdendo qualità, il cambio può evitare errori nel finale.`:`${p.player_name} comincia a perdere brillantezza: le corse sono meno esplosive e lo staff segnala ${Math.round(energy)}% di energia residua.`;add(minute,side==='user'&&energy<63?'fatigue_warning':'fatigue',side,p,desc,{energy:Math.round(energy)})}};
 const fatigueMistake=(side:'user'|'opp',p:Starter|null|undefined,minute:number,phase:'attack'|'defence')=>{if(!p)return false;const energy=liveEnergy(p,minute);if(energy>=60)return false;const chance=clamp(.035+(60-energy)*.009,.035,.23);if(rnd()>=chance)return false;maybeFatigue(side,p,minute);add(minute,'error',side,p,phase==='attack'?`${p.player_name} è poco lucido: il controllo si allunga e l'azione sfuma. La stanchezza comincia a pesare.`:`${p.player_name} arriva tardi sulla lettura e apre uno spazio pericoloso. La fatica gli costa un errore.`,{energy:Math.round(energy)});return true};
 const card=(side:'user'|'opp',player:Starter|null,minute:number,reason:string,directRedChance=.012)=>{if(!player)return;const sent=side==='user'?sentOffUser:sentOffOpp;if(sent.has(player.player_id))return;if(rnd()<directRedChance){add(minute,'red',side,player,player.player_name+' entra in modo scomposto. Rosso diretto: '+reason);sent.add(player.player_id);return}const n=(yellows.get(player.player_id)||0)+1;yellows.set(player.player_id,n);add(minute,'yellow',side,player,player.player_name+' '+reason+(n===2?' È il secondo giallo.':''));if(n>=2){add(minute+1,'red',side,player,'SECONDO GIALLO — '+player.player_name+' viene espulso. La squadra resta in dieci.');sent.add(player.player_id)}};
 const injuryProfile=()=>{
   const r=rnd();
   if(r<.23){const weeks=rnd()<.72?0:1;return{label:"contusione",category:"traumatic" as const,severity:weeks===0?"minor" as const:"moderate" as const,weeks,action:"resta a terra dopo il contrasto e chiede l’intervento dello staff",detail:weeks===0?"Il colpo sembra gestibile: verrà rivalutato nelle prossime ore.":"La botta è più seria del previsto: la prossima gara è in dubbio."}}
   if(r<.41){const weeks=rnd()<.66?1:rnd()<.86?2:3;return{label:"distorsione alla caviglia",category:"traumatic" as const,severity:weeks<=1?"moderate" as const:"serious" as const,weeks,action:"appoggia male il piede dopo un duello e si ferma subito",detail:weeks===1?"Lo staff teme uno stop breve.":weeks===2?"La caviglia richiederà almeno un paio di settimane.":"La distorsione appare importante: il recupero non sarà immediato."}}
   if(r<.63){const weeks=rnd()<.72?1:2;return{label:"affaticamento muscolare",category:"muscular" as const,severity:"moderate" as const,weeks,action:"si ferma durante uno scatto e porta subito la mano alla coscia",detail:weeks===1?"Il muscolo va protetto: probabile assenza nella prossima gara.":"Lo staff preferisce non rischiare: servirà un recupero più graduale."}}
   if(r<.79){const weeks=rnd()<.62?2:rnd()<.88?3:4;return{label:"stiramento muscolare",category:"muscular" as const,severity:weeks<=2?"moderate" as const:"serious" as const,weeks,action:"interrompe improvvisamente la corsa e segnala un dolore muscolare",detail:weeks===2?"Il quadro suggerisce uno stop di circa due settimane.":"Il problema muscolare è significativo: servirà qualche settimana."}}
   if(r<.88){const weeks=4+Math.floor(rnd()*3);return{label:"lesione muscolare",category:"muscular" as const,severity:"serious" as const,weeks,action:"si blocca senza contatto e chiede immediatamente il cambio",detail:"La prima valutazione fa pensare a una lesione: lo stop sarà di diverse settimane."}}
   if(r<.97){const weeks=2+Math.floor(rnd()*4);return{label:"trauma al ginocchio",category:"traumatic" as const,severity:"serious" as const,weeks,action:"subisce una torsione del ginocchio nel contrasto e non riesce a continuare",detail:"Serviranno esami e prudenza: il rientro non è imminente."}}
   const weeks=8+Math.floor(rnd()*9);return{label:"lesione legamentosa",category:"traumatic" as const,severity:"major" as const,weeks,action:"cade male dopo il contrasto e il ginocchio cede: lo staff chiede subito il cambio",detail:"I segnali sono preoccupanti: si prospetta uno stop lungo e un percorso di recupero complesso."}
 };
 const sideName=(us:boolean)=>us?"La squadra":opp;
 const byRole=(pool:Starter[],role:string)=>pool.filter(p=>p.role===role);
 const choose=(pool:Starter[],kind:'shot'|'creator'|'defender',fallbackRole?:string)=>{if(!pool.length)return null;const filtered=fallbackRole?byRole(pool,fallbackRole):[];return pick(rnd,filtered.length?filtered:pool,kind)};
 const deadBallTaker=(pool:Starter[],kind:"penalty"|"setpiece")=>{const eligible=pool.filter(p=>kind==="penalty"?p.penaltyTaker:p.setPieceTaker).sort((a,b)=>Number(kind==="penalty"?a.penaltyOrder??99:a.setPieceOrder??99)-Number(kind==="penalty"?b.penaltyOrder??99:b.setPieceOrder??99));return eligible[0]||choose(pool,'shot',kind==="penalty"?"A":"C")};
 const quality=(p:Starter|null|undefined,minute=45)=>{if(!p)return 1;const energy=liveEnergy(p,minute),fatigueFactor=clamp(.68+(energy/100)*.32,.80,1);return confidenceFactor(p.confidence,p.managerTrust??50)*(0.86+Number(p.strength||55)/250)*fatigueFactor};
 const finish=(us:boolean,minute:number,shotter:Starter|null,creator:Starter|null,contextBoost=0,kind="azione")=>{
   const trailing=usGoals<opGoals,late=minute>70,base=.045+rnd()*.15,xg=Number(clamp(base+contextBoost+(late&&trailing?.035:0)+streakBoost*.1,.025,.62).toFixed(3)),q=quality(shotter,minute),onTarget=rnd()<clamp(.34+xg*.52+(q-1)*.11,.28,.72),goal=rnd()<clamp(xg*q*(1.02+streakBoost*.6),.015,.74),woodwork=!goal&&rnd()<clamp(.055+xg*.12,.045,.13),side=us?'user':'opp';
   maybeFatigue(side,shotter,minute);if(fatigueMistake(side,shotter,minute,'attack'))return;add(minute,'shot_attempt',side,shotter,(shotter?.player_name||opp)+' prende la mira e calcia verso la porta.',{assist:creator&&creator.player_id!==shotter?.player_id?creator:null});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+1,'goal',side,shotter,(us?'GOL! ':'GOL '+opp+'! ')+(shotter?.player_name||opp)+' trova il varco e manda il pallone in rete! Lo stadio esplode mentre i compagni corrono ad abbracciarlo. Chance da '+xg.toFixed(2)+' xG.',{assist:creator&&creator.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:true});return}
   if(woodwork){add(minute+1,'woodwork',side,shotter,rnd()<.5?'Il pallone si stampa sul palo!':'La conclusione centra in pieno la traversa!',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:false});return}if(onTarget){add(minute+1,'shot_saved',side,shotter,'Il portiere legge la traiettoria e respinge il pallone.',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:true});if(!us){const gk=activePool(ps,'user').find(p=>p.role==='P');if(gk)add(minute+1,'keeper_save','user',gk,gk.player_name+' completa l’intervento, blocca la seconda palla e fa ripartire la squadra.')}}
   else add(minute+1,'shot_missed',side,shotter,'Il pallone sfila fuori dallo specchio della porta.',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:false});
 };
 const counterChain=(us:boolean,minute:number)=>{
   const own=activePool(us?ps:oppPs,us?'user':'opp'),other=activePool(us?oppPs:ps,us?'opp':'user');if(!own.length)return;
   const oppAtt=choose(other,'shot','A'),def=choose(own,'defender','D'),mid=choose(own,'creator','C'),att=choose(own,'shot','A');
   add(minute,'action',us?'opp':'user',oppAtt,(oppAtt?.player_name||sideName(!us))+' punta il proprio marcatore e prova a creare superiorità nell’ultimo terzo.');
   const win=rnd()<clamp(.53+(quality(def,minute)-1)*.45+((style==='Pressing'&&us) ? .05 : 0),.34,.72);
   if(!win){add(minute,'duel',us?'opp':'user',oppAtt,(oppAtt?.player_name||sideName(!us))+' riesce a superare il primo contrasto e tiene viva l’azione.');if(rnd()<.22){const fouler=choose(own,'defender','D');card(us?'user':'opp',fouler,minute+1,'ferma la ripartenza con un fallo tattico e viene ammonito.',.006);return}resolveAttack(!us,minute+1,oppAtt,choose(other,'creator','C'),.025,"l'azione insistita",.18);return}
   if(fatigueMistake(us?'user':'opp',def,minute,'defence')){resolveAttack(!us,minute+1,oppAtt,choose(other,'creator','C'),.05,"l'errore difensivo",.24);return}
   add(minute,'duel',us?'user':'opp',def,(def?.player_name||sideName(us))+' legge il dribbling, entra con il tempo giusto e recupera il pallone.');
   add(minute,'transition',us?'user':'opp',mid,(def?.player_name||"Il difensore")+' scarica subito su '+(mid?.player_name||"un centrocampista")+', che riceve fronte alla porta e alza la testa.');
   const through=rnd()<clamp(.55+((style==='Contropiede'&&us) ? .14 : 0)+((style==='Verticale'&&us) ? .10 : 0)+(quality(mid,minute)-1)*.3,.38,.79);
   if(!through){add(minute+1,'action',us?'user':'opp',mid,(mid?.player_name||"Il centrocampista")+' cerca il passaggio verticale, ma la linea avversaria intercetta e spegne la ripartenza.');return}
   add(minute+1,'transition',us?'user':'opp',mid,(mid?.player_name||"Il centrocampista")+' vede il movimento in profondità e infila un passaggio filtrante alle spalle della difesa.');
   const control=rnd()<clamp(.62+(quality(att,minute)-1)*.38,.42,.84);
   if(!control){add(minute+1,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' scatta sul filtrante ma il controllo lo rallenta: il portiere esce e fa sua la palla.');return}
   add(minute+1,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' attacca la profondità, controlla in corsa e si presenta davanti al portiere.');
   const dribble=rnd()<clamp(.46+(quality(att,minute)-1)*.32+((style==='Contropiede'&&us) ? .05 : 0),.28,.68);
   if(dribble){add(minute+2,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' prova a saltare il portiere con un ultimo tocco e si apre lo specchio.');resolveAttack(us,minute+2,att,mid,.10,"il contropiede",.32)}
   else{add(minute+2,'shot_saved',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' prova a superare il portiere, ma l’estremo difensore resta in piedi e chiude lo spazio.',{xg:.16,shotOnTarget:true});if(!us){const gk=activePool(ps,'user').find(p=>p.role==='P');if(gk)add(minute+2,'keeper_save','user',gk,gk.player_name+' vince il duello uno contro uno e salva la squadra.')}}
 };
 const penaltyChain=(us:boolean,minute:number)=>{
   const own=activePool(us?ps:oppPs,us?'user':'opp');if(!own.length)return;const taker=deadBallTaker(own,"penalty"),side=us?'user':'opp',q=quality(taker,minute),xg=.76,goal=rnd()<clamp(.72+(q-1)*.22,.60,.88),saved=!goal&&rnd()<.72;
   add(minute,'penalty_awarded',side,taker,'L’arbitro indica il dischetto: calcio di rigore.');
   add(minute+1,'penalty_awarded',side,taker,(taker?.player_name||"Il rigorista")+' prende il pallone e si presenta sul dischetto.');
   add(minute+2,'shot_attempt',side,taker,(taker?.player_name||"Il rigorista")+' parte nella rincorsa e calcia il rigore.',{xg});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+3,'goal',side,taker,(us?'GOL! ':'GOL '+opp+'! ')+(taker?.player_name||opp)+' è freddissimo dal dischetto e trasforma il rigore!',{xg,shotOnTarget:true});return}
   if(saved){add(minute+3,'penalty_saved',side,taker,'Il portiere intuisce l’angolo e respinge il calcio di rigore!',{xg,shotOnTarget:true});if(!us){const gk=activePool(ps,'user').find(p=>p.role==='P');if(gk)add(minute+3,'keeper_save','user',gk,gk.player_name+' para il rigore e salva la squadra.')}return}
   add(minute+3,'shot_missed',side,taker,'Il rigore termina fuori: occasione enorme sprecata.',{xg,shotOnTarget:false});
 };
 const freeKickChain=(us:boolean,minute:number)=>{
   const own=activePool(us?ps:oppPs,us?'user':'opp');if(!own.length)return;const taker=deadBallTaker(own,"setpiece"),side=us?'user':'opp',q=quality(taker,minute),xg=Number(clamp(.055+(q-1)*.12+rnd()*.08,.035,.20).toFixed(3)),onTarget=rnd()<clamp(.37+(q-1)*.28,.28,.64),goal=rnd()<clamp(xg*q,.025,.24);
   add(minute,'free_kick',side,taker,'Punizione da posizione interessante.');
   add(minute+1,'free_kick',side,taker,(taker?.player_name||"Il tiratore")+' sistema il pallone e prende qualche passo di rincorsa.');
   add(minute+2,'shot_attempt',side,taker,(taker?.player_name||"Il tiratore")+' calcia direttamente verso la porta.',{xg});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+3,'goal',side,taker,(us?'GOL! ':'GOL '+opp+'! ')+(taker?.player_name||opp)+' disegna una punizione perfetta e trova la rete!',{xg,shotOnTarget:true});return}
   if(onTarget){add(minute+3,'shot_saved',side,taker,'Il portiere vola sulla traiettoria e respinge la punizione.',{xg,shotOnTarget:true});return}
   add(minute+3,'shot_missed',side,taker,'La punizione supera la barriera ma finisce fuori dallo specchio.',{xg,shotOnTarget:false});
 };
 const resolveAttack=(us:boolean,minute:number,shotter:Starter|null,creator:Starter|null,contextBoost=0,context="l'azione",insideChance=.24)=>{
   const other=activePool(us?oppPs:ps,us?'opp':'user'),side=us?'user':'opp',defSide=us?'opp':'user',outcome=rnd();
   maybeFatigue(side,shotter,minute);if(fatigueMistake(side,shotter,minute,'attack'))return;
   if(outcome<.64){finish(us,minute,shotter,creator,contextBoost,context);return}
   if(outcome<.86){const defender=choose(other,'defender','D');maybeFatigue(defSide,defender,minute);if(fatigueMistake(defSide,defender,minute,'defence')){finish(us,minute+1,shotter,creator,contextBoost+.035,"l'errore difensivo");return}add(minute,'duel',defSide,defender,(defender?.player_name||"Il difensore")+' legge la giocata, chiude lo spazio e ferma l’azione prima del tiro.');return}
   const defender=choose(other,'defender','D'),inArea=rnd()<insideChance;
   add(minute,'foul',defSide,defender,(defender?.player_name||"Il difensore")+' arriva in ritardo sul portatore di palla e commette fallo.');if(rnd()<(inArea?.34:.22))card(defSide,defender,minute+1,inArea?'interrompe una chiara occasione in area e viene sanzionato.':'ferma un attacco promettente e finisce sul taccuino dell’arbitro.',inArea?.018:.007);
   if(inArea)penaltyChain(us,minute+1);else freeKickChain(us,minute+1);
 };
 const possessionChain=(us:boolean,minute:number)=>{
   const own=activePool(us?ps:oppPs,us?'user':'opp');if(!own.length)return;const d=choose(own,'defender','D'),m1=choose(own,'creator','C'),m2=choose(own,'creator','C'),a=choose(own,'shot','A');
   add(minute,'possession',us?'user':'opp',d,(d?.player_name||sideName(us))+' apre la costruzione dal basso e aspetta che il pressing si muova.');
   add(minute,'possession',us?'user':'opp',m1,(m1?.player_name||"Il centrocampista")+' viene incontro, riceve tra le linee di pressione e gira il gioco con un tocco.');
   if(rnd()<.28){add(minute+1,'duel',us?'opp':'user',null,'La pressione avversaria arriva in tempo e forza una giocata sporca: il possesso cambia padrone.');return}
   add(minute+1,'action',us?'user':'opp',m2,(m2?.player_name||"Un altro centrocampista")+' trova spazio tra le linee e punta la zona centrale.');
   if(rnd()<clamp(.55+((style==='Possesso'&&us) ? .12 : 0)+((style==='Verticale'&&us) ? .05 : 0),.4,.75)){add(minute+1,'action',us?'user':'opp',a,(a?.player_name||"L'attaccante")+' viene incontro, appoggia di prima e poi attacca subito lo spazio alle spalle del centrale.');add(minute+2,'transition',us?'user':'opp',m2,(m2?.player_name||"Il centrocampista")+' legge il movimento, chiude l’uno-due e infila il pallone nello spazio.');add(minute+2,'action',us?'user':'opp',a,(a?.player_name||"L'attaccante")+' si inserisce alle spalle dei difensori e riceve in corsa, con la porta davanti.');resolveAttack(us,minute+3,a,m2,.035,"la manovra costruita",.24)}else add(minute+2,'possession',us?'user':'opp',m2,(m2?.player_name||"Il centrocampista")+' non trova il varco e preferisce ricominciare, mantenendo il possesso.');
 };
 const pressChain=(us:boolean,minute:number)=>{
   const own=activePool(us?ps:oppPs,us?'user':'opp'),other=activePool(us?oppPs:ps,us?'opp':'user');if(!own.length)return;const presser=choose(own,'creator','C'),victim=choose(other,'defender','D'),att=choose(own,'shot','A');
   add(minute,'possession',us?'opp':'user',victim,(victim?.player_name||sideName(!us))+' riceve vicino alla propria area e prova a uscire palla al piede.');
   add(minute,'press',us?'user':'opp',presser,(presser?.player_name||sideName(us))+' accorcia forte e chiude la linea di passaggio.');
   maybeFatigue(us?'user':'opp',presser,minute);if(fatigueMistake(us?'user':'opp',presser,minute,'defence')){add(minute+1,'action',us?'opp':'user',victim,(victim?.player_name||sideName(!us))+' approfitta del pressing fuori tempo e supera la prima pressione.');return}
   if(rnd()<clamp(.48+((style==='Pressing'&&us) ? .18 : 0)+(quality(presser,minute)-1)*.35,.32,.75)){add(minute,'transition',us?'user':'opp',presser,(presser?.player_name||"Il centrocampista")+' ruba palla in zona alta e serve immediatamente '+(att?.player_name||"l'attaccante")+' dentro l’area.');resolveAttack(us,minute+1,att,presser,.075,"il recupero alto",.30)}
   else{add(minute+1,'action',us?'opp':'user',victim,(victim?.player_name||sideName(!us))+' resiste alla pressione, protegge palla e trova l’uomo libero per uscire.');if(rnd()<.18)card(us?'user':'opp',presser,minute+1,'arriva un attimo in ritardo nel tentativo di recuperare: fallo netto e cartellino giallo.',.005)}
 };
 while(m<88){
   m+=3+Math.floor(rnd()*3);if(m>=90)break;if(m>43&&m<48)m=48;
   const trailing=usGoals<opGoals,leading=usGoals>opGoals,late=m>70,numEdge=sentOffOpp.size-sentOffUser.size,attackShare=clamp(usShare+(late&&trailing?.045:0)-(late&&leading?.02:0)+numEdge*.055,.27,.74),us=rnd()<attackShare;
   const r=rnd(),mindAttack=us&&mentality==='attack',mindDefend=us&&mentality==='defend',counterChance=((style==='Contropiede'&&us) ? .34 : .20)+((style==='Verticale'&&us) ? .08 : 0)+(mindAttack ? .05 : 0),pressChance=((style==='Pressing'&&us) ? .27 : .15)+(mindAttack ? .05 : 0)-(mindDefend ? .04 : 0),possessionChance=((style==='Possesso'&&us) ? .38 : .25)+(mindDefend ? .08 : 0);
   if(r<counterChance)counterChain(us,m);
   else if(r<counterChance+pressChance)pressChain(us,m);
   else if(r<counterChance+pressChance+possessionChance)possessionChain(us,m);
   else{const own=activePool(us?ps:oppPs,us?'user':'opp'),other=activePool(us?oppPs:ps,us?'opp':'user'),creator=choose(own,'creator','C'),shotter=choose(own,'shot','A');add(m,'action',us?'user':'opp',creator,(creator?.player_name||sideName(us))+' riceve tra le linee, porta palla in avanti e cerca un compagno nell’ultimo terzo.');if(rnd()<.56)resolveAttack(us,m+1,shotter,creator,.015,"l'azione",.20);else{const defender=choose(other,'defender','D');maybeFatigue(us?'opp':'user',defender,m+1);if(fatigueMistake(us?'opp':'user',defender,m+1,'defence'))resolveAttack(us,m+2,shotter,creator,.04,"l'errore difensivo",.25);else{add(m+1,'duel',us?'opp':'user',defender,(defender?.player_name||"Il difensore")+' legge l’ultimo passaggio, esce in anticipo e interrompe la giocata.');if(rnd()<.19)card(us?'opp':'user',defender,m+2,'trattiene l’avversario per evitare che riparta subito: l’arbitro estrae il cartellino giallo.',.004)}}}
   if(injuryCount<1&&rnd()<.0045){const injurySide=rnd()<.58?'user':'opp',pool=activePool(injurySide==='user'?ps:oppPs,injurySide),inj=pool.length?pool[Math.floor(rnd()*pool.length)]:null;if(inj){const profile=injuryProfile();add(m+2,'injury',injurySide,inj,inj.player_name+' '+profile.action+'. '+profile.detail,{injuryWeeks:profile.weeks,injuryLabel:profile.label,injuryCategory:profile.category,injurySeverity:profile.severity});injuryCount++}}
 }
 add(45,'phase','user',null,'INTERVALLO — il primo tempo entra nell’analisi dello staff.');
 out.sort((a,b)=>a.minute-b.minute);
 return out
}

export function buildPlayerStats(run:string,round:number,starters:Starter[],events:MatchEvent[]){const rnd=seeded(`${run}|g${round}|stats3`),oppGoals=events.filter(e=>e.side==='opp'&&e.type==='goal').length,oppShots=events.filter(e=>e.side==='opp'&&e.xg!=null);return starters.map(p=>{const pe=events.filter(e=>e.side==='user'&&e.player?.player_id===p.player_id),assists=events.filter(e=>e.side==='user'&&e.assist?.player_id===p.player_id&&e.type==='goal').length,shots=pe.filter(e=>e.xg!=null).length,sot=pe.filter(e=>e.xg!=null&&e.shotOnTarget).length,xg=pe.reduce((a,e)=>a+Number(e.xg||0),0),goals=pe.filter(e=>e.type==='goal').length,errors=pe.filter(e=>e.type==='error').length,yellows=pe.filter(e=>e.type==='yellow').length,reds=pe.filter(e=>e.type==='red').length;if(p.role==='P'){const saves=events.filter(e=>e.type==='keeper_save'&&e.player?.player_id===p.player_id).length||Math.max(0,oppShots.filter(e=>e.shotOnTarget).length-oppGoals),rating=clamp(6+saves*.22+(oppGoals===0?.35:0)-oppGoals*.16-errors*.7-reds*.55,4.5,9.3);return{player_id:p.player_id,player_name:p.player_name,rating:+rating.toFixed(1),goals:0,chances:0,recoveries:0,duels:0,progressions:0,dangerous_errors:errors,saves,goals_conceded:oppGoals,interventions:saves+Math.round(rnd()*3),shots:0,shots_on_target:0,assists:0,xg:0,yellow_cards:yellows,red_cards:reds,fouls:yellows}}
 const rec=Math.round((p.role==='D'?6:p.role==='C'?5:2)+pe.filter(e=>e.type==='press').length*2+rnd()*2),duels=Math.round((p.role==='D'?6:p.role==='C'?4:2)+pe.filter(e=>e.type==='duel').length*2+rnd()*2),prog=Math.round((p.role==='C'?5:p.role==='A'?4:2)+pe.filter(e=>['transition','possession','action'].includes(e.type)).length*1.5+rnd()*2),activity=goals*1.05+assists*.65+sot*.18+rec*.03+duels*.025+prog*.035-errors*.7-reds*.5,rating=clamp(5.65+activity+(p.confidence-50)*.006+(rnd()-.5)*.3,4.5,9.4);return{player_id:p.player_id,player_name:p.player_name,rating:+rating.toFixed(1),goals,chances:shots,recoveries:rec,duels,progressions:prog,dangerous_errors:errors,saves:0,goals_conceded:0,interventions:0,shots,shots_on_target:sot,assists,xg:+xg.toFixed(3),yellow_cards:yellows,red_cards:reds,fouls:yellows}})}
export function matchSummary(events:MatchEvent[]){const side=(s:'user'|'opp')=>{const e=events.filter(x=>x.side===s),shots=e.filter(x=>x.xg!=null),goals=e.filter(x=>x.type==='goal').length;return{goals,shots:shots.length,onTarget:shots.filter(x=>x.shotOnTarget).length,xg:+shots.reduce((a,x)=>a+Number(x.xg||0),0).toFixed(2),corners:e.filter(x=>x.type==='setpiece').length,yellows:e.filter(x=>x.type==='yellow').length,reds:e.filter(x=>x.type==='red').length}};return{user:side('user'),opp:side('opp')}}