export type Fixture={home_code:string;away_code:string};
export type CpuResult=Fixture&{home_goals:number;away_goals:number;is_user_match:boolean};
export type Starter={player_id:string;player_name:string;role:string;confidence:number;managerTrust?:number|null;strength?:number|null;penaltyTaker?:boolean;penaltyOrder?:number|null;setPieceTaker?:boolean;setPieceOrder?:number|null};
export type MatchEvent={minute:number;type:string;side:'user'|'opp';player?:Starter|null;assist?:Starter|null;desc:string;xg?:number;shotOnTarget?:boolean;x?:number;y?:number;injuryWeeks?:number;injuryLabel?:string};
export function seeded(seed:string){let h=2166136261;for(const c of seed)h=Math.imul(h^c.charCodeAt(0),16777619);return()=>((h=Math.imul(h^(h>>>15),2246822519))>>>0)/4294967296}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));function poisson(lambda:number,rnd:()=>number){const L=Math.exp(-lambda);let p=1,k=0;do{k++;p*=Math.max(.000001,rnd())}while(p>L&&k<9);return clamp(k-1,0,6)}
export function confidenceFactor(c:number,trust=50){const conf=clamp((c-50)/50,-1,1)*.06,rel=clamp((trust-50)/50,-1,1)*.035;return 1+conf+rel}
export function clubStrength(rows:{team_nfl:string|null;fvm_fc:number|null;quotazione_fc:number|null}[]){const by:Record<string,number[]>={};for(const p of rows){if(!p.team_nfl)continue;(by[p.team_nfl]??=[]).push(Number(p.fvm_fc||p.quotazione_fc||1))}const out:Record<string,number>={};for(const [club,vals] of Object.entries(by)){vals.sort((a,b)=>b-a);const xi=vals.slice(0,11);out[club]=xi.length?xi.reduce((a,b)=>a+b,0)/xi.length:1}return out}
export function simulateCpuFixture(run:string,round:number,f:Fixture,strength:Record<string,number>):CpuResult{const rnd=seeded(`${run}|g${round}|${f.home_code}|${f.away_code}`),h=strength[f.home_code]||50,a=strength[f.away_code]||50,diff=clamp((h-a)/Math.max(30,(h+a)/2),-.45,.45);return{...f,home_goals:poisson(clamp(1.51+.55*diff,.45,2.35),rnd),away_goals:poisson(clamp(1.20-.55*diff,.35,2.2),rnd),is_user_match:false}}
function pick(rnd:()=>number,ps:Starter[],kind:'shot'|'creator'|'defender'){const rw:any=kind==='shot'?{P:.001,D:.22,C:.7,A:1.8}:kind==='creator'?{P:.03,D:.45,C:1.45,A:1.1}:{P:.1,D:1.7,C:1,A:.35};const w=ps.map(p=>(rw[p.role]||1)*confidenceFactor(p.confidence,p.managerTrust??50)*(0.72+Math.min(1.5,Number(p.strength||55)/75))),t=w.reduce((a,b)=>a+b,0);let x=rnd()*t;for(let i=0;i<ps.length;i++){x-=w[i];if(x<=0)return ps[i]}return ps[ps.length-1]}
export function buildMatchEvents(run:string,round:number,style:string,opp:string,ps:Starter[],oppPs:Starter[]=[],dryStreak=0,mentality:'attack'|'balanced'|'defend'='balanced'){
 const rnd=seeded(`${run}|g${round}|${style}|${mentality}|match7`),coordRnd=seeded(`${run}|g${round}|${style}|${mentality}|coords3`),out:MatchEvent[]=[];
 const avg=ps.reduce((a,p)=>a+Number(p.strength||55),0)/Math.max(1,ps.length),oppAvg=oppPs.reduce((a,p)=>a+Number(p.strength||55),0)/Math.max(1,oppPs.length||1),conf=ps.reduce((a,p)=>a+p.confidence,0)/Math.max(1,ps.length),trust=ps.reduce((a,p)=>a+Number(p.managerTrust??50),0)/Math.max(1,ps.length);
 const styleShare:any={Equilibrato:.50,Possesso:.55,Verticale:.51,Contropiede:.47,Pressing:.53},streakBoost=clamp(dryStreak*.045,0,.16),strengthEdge=oppPs.length?clamp((avg-oppAvg)/180,-.07,.07):0;
 const mentalityShare=mentality==='attack'?.055:mentality==='defend'?-.045:0,usShare=clamp((styleShare[style]||.5)+mentalityShare+strengthEdge+(conf-50)*.0007+(trust-50)*.00035,.36,.66);
 let usGoals=0,opGoals=0,m=2,injuryCount=0;
 const add=(minute:number,type:string,side:'user'|'opp',player:Starter|null|undefined,desc:string,extra:any={})=>{const dir=side==='user'?1:-1,base=type==='goal'?94:type==='shot_saved'||type==='shot_missed'||type==='shot_attempt'?86:type==='press'?68:type==='transition'?64:type==='action'?70:type==='duel'?52:type==='possession'?35:type==='keeper_save'?8:50,x=extra.x??(dir===1?base:100-base),y=extra.y??(18+coordRnd()*64);out.push({minute:Math.min(89,minute),type,side,player:player||null,desc,x:+clamp(x,3,97).toFixed(1),y:+clamp(y,7,93).toFixed(1),...extra})};
 const sideName=(us:boolean)=>us?"La squadra":opp;
 const byRole=(pool:Starter[],role:string)=>pool.filter(p=>p.role===role);
 const choose=(pool:Starter[],kind:'shot'|'creator'|'defender',fallbackRole?:string)=>{if(!pool.length)return null;const filtered=fallbackRole?byRole(pool,fallbackRole):[];return pick(rnd,filtered.length?filtered:pool,kind)};
 const deadBallTaker=(pool:Starter[],kind:"penalty"|"setpiece")=>{const eligible=pool.filter(p=>kind==="penalty"?p.penaltyTaker:p.setPieceTaker).sort((a,b)=>Number(kind==="penalty"?a.penaltyOrder??99:a.setPieceOrder??99)-Number(kind==="penalty"?b.penaltyOrder??99:b.setPieceOrder??99));return eligible[0]||choose(pool,'shot',kind==="penalty"?"A":"C")};
 const quality=(p:Starter|null|undefined)=>p?confidenceFactor(p.confidence,p.managerTrust??50)*(0.86+Number(p.strength||55)/250):1;
 const finish=(us:boolean,minute:number,shotter:Starter|null,creator:Starter|null,contextBoost=0,kind="azione")=>{
   const trailing=usGoals<opGoals,late=minute>70,base=.045+rnd()*.15,xg=Number(clamp(base+contextBoost+(late&&trailing?.035:0)+streakBoost*.1,.025,.62).toFixed(3)),q=quality(shotter),onTarget=rnd()<clamp(.34+xg*.52+(q-1)*.11,.28,.72),goal=rnd()<clamp(xg*q*(1.02+streakBoost*.6),.015,.74),woodwork=!goal&&rnd()<clamp(.055+xg*.12,.045,.13),side=us?'user':'opp';
   add(minute,'shot_attempt',side,shotter,(shotter?.player_name||opp)+' prende la mira e calcia verso la porta.',{assist:creator&&creator.player_id!==shotter?.player_id?creator:null});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+1,'goal',side,shotter,(us?'GOL! ':'GOL '+opp+'! ')+(shotter?.player_name||opp)+' trova il varco e manda il pallone in rete! Lo stadio esplode mentre i compagni corrono ad abbracciarlo. Chance da '+xg.toFixed(2)+' xG.',{assist:creator&&creator.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:true});return}
   if(woodwork){add(minute+1,'woodwork',side,shotter,rnd()<.5?'Il pallone si stampa sul palo!':'La conclusione centra in pieno la traversa!',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:false});return}if(onTarget){add(minute+1,'shot_saved',side,shotter,'Il portiere legge la traiettoria e respinge il pallone.',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:true});if(!us){const gk=ps.find(p=>p.role==='P');if(gk)add(minute+1,'keeper_save','user',gk,gk.player_name+' completa l’intervento, blocca la seconda palla e fa ripartire la squadra.')}}
   else add(minute+1,'shot_missed',side,shotter,'Il pallone sfila fuori dallo specchio della porta.',{assist:us&&creator?.player_id!==shotter?.player_id?creator:null,xg,shotOnTarget:false});
 };
 const counterChain=(us:boolean,minute:number)=>{
   const own=us?ps:oppPs,other=us?oppPs:ps;if(!own.length)return;
   const oppAtt=choose(other,'shot','A'),def=choose(own,'defender','D'),mid=choose(own,'creator','C'),att=choose(own,'shot','A');
   add(minute,'action',us?'opp':'user',oppAtt,(oppAtt?.player_name||sideName(!us))+' punta il proprio marcatore e prova a creare superiorità nell’ultimo terzo.');
   const win=rnd()<clamp(.53+(quality(def)-1)*.45+((style==='Pressing'&&us) ? .05 : 0),.34,.72);
   if(!win){add(minute,'duel',us?'opp':'user',oppAtt,(oppAtt?.player_name||sideName(!us))+' riesce a superare il primo contrasto e tiene viva l’azione.');if(rnd()<.22){const fouler=choose(own,'defender','D');add(minute+1,'yellow',us?'user':'opp',fouler,(fouler?.player_name||"Il difensore")+' capisce che la ripartenza sta diventando pericolosa, spende il fallo tattico e viene ammonito.');return}resolveAttack(!us,minute+1,oppAtt,choose(other,'creator','C'),.025,"l'azione insistita",.18);return}
   add(minute,'duel',us?'user':'opp',def,(def?.player_name||sideName(us))+' legge il dribbling, entra con il tempo giusto e recupera il pallone.');
   add(minute,'transition',us?'user':'opp',mid,(def?.player_name||"Il difensore")+' scarica subito su '+(mid?.player_name||"un centrocampista")+', che riceve fronte alla porta e alza la testa.');
   const through=rnd()<clamp(.55+((style==='Contropiede'&&us) ? .14 : 0)+((style==='Verticale'&&us) ? .10 : 0)+(quality(mid)-1)*.3,.38,.79);
   if(!through){add(minute+1,'action',us?'user':'opp',mid,(mid?.player_name||"Il centrocampista")+' cerca il passaggio verticale, ma la linea avversaria intercetta e spegne la ripartenza.');return}
   add(minute+1,'transition',us?'user':'opp',mid,(mid?.player_name||"Il centrocampista")+' vede il movimento in profondità e infila un passaggio filtrante alle spalle della difesa.');
   const control=rnd()<clamp(.62+(quality(att)-1)*.38,.42,.84);
   if(!control){add(minute+1,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' scatta sul filtrante ma il controllo lo rallenta: il portiere esce e fa sua la palla.');return}
   add(minute+1,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' attacca la profondità, controlla in corsa e si presenta davanti al portiere.');
   const dribble=rnd()<clamp(.46+(quality(att)-1)*.32+((style==='Contropiede'&&us) ? .05 : 0),.28,.68);
   if(dribble){add(minute+2,'action',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' prova a saltare il portiere con un ultimo tocco e si apre lo specchio.');resolveAttack(us,minute+2,att,mid,.10,"il contropiede",.32)}
   else{add(minute+2,'shot_saved',us?'user':'opp',att,(att?.player_name||"L'attaccante")+' prova a superare il portiere, ma l’estremo difensore resta in piedi e chiude lo spazio.',{xg:.16,shotOnTarget:true});if(!us){const gk=ps.find(p=>p.role==='P');if(gk)add(minute+2,'keeper_save','user',gk,gk.player_name+' vince il duello uno contro uno e salva la squadra.')}}
 };
 const penaltyChain=(us:boolean,minute:number)=>{
   const own=us?ps:oppPs;if(!own.length)return;const taker=deadBallTaker(own,"penalty"),side=us?'user':'opp',q=quality(taker),xg=.76,goal=rnd()<clamp(.72+(q-1)*.22,.60,.88),saved=!goal&&rnd()<.72;
   add(minute,'penalty_awarded',side,taker,'L’arbitro indica il dischetto: calcio di rigore.');
   add(minute+1,'penalty_awarded',side,taker,(taker?.player_name||"Il rigorista")+' prende il pallone e si presenta sul dischetto.');
   add(minute+2,'shot_attempt',side,taker,(taker?.player_name||"Il rigorista")+' parte nella rincorsa e calcia il rigore.',{xg});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+3,'goal',side,taker,(us?'GOL! ':'GOL '+opp+'! ')+(taker?.player_name||opp)+' è freddissimo dal dischetto e trasforma il rigore!',{xg,shotOnTarget:true});return}
   if(saved){add(minute+3,'penalty_saved',side,taker,'Il portiere intuisce l’angolo e respinge il calcio di rigore!',{xg,shotOnTarget:true});if(!us){const gk=ps.find(p=>p.role==='P');if(gk)add(minute+3,'keeper_save','user',gk,gk.player_name+' para il rigore e salva la squadra.')}return}
   add(minute+3,'shot_missed',side,taker,'Il rigore termina fuori: occasione enorme sprecata.',{xg,shotOnTarget:false});
 };
 const freeKickChain=(us:boolean,minute:number)=>{
   const own=us?ps:oppPs;if(!own.length)return;const taker=deadBallTaker(own,"setpiece"),side=us?'user':'opp',q=quality(taker),xg=Number(clamp(.055+(q-1)*.12+rnd()*.08,.035,.20).toFixed(3)),onTarget=rnd()<clamp(.37+(q-1)*.28,.28,.64),goal=rnd()<clamp(xg*q,.025,.24);
   add(minute,'free_kick',side,taker,'Punizione da posizione interessante.');
   add(minute+1,'free_kick',side,taker,(taker?.player_name||"Il tiratore")+' sistema il pallone e prende qualche passo di rincorsa.');
   add(minute+2,'shot_attempt',side,taker,(taker?.player_name||"Il tiratore")+' calcia direttamente verso la porta.',{xg});
   if(goal){if(us)usGoals++;else opGoals++;add(minute+3,'goal',side,taker,(us?'GOL! ':'GOL '+opp+'! ')+(taker?.player_name||opp)+' disegna una punizione perfetta e trova la rete!',{xg,shotOnTarget:true});return}
   if(onTarget){add(minute+3,'shot_saved',side,taker,'Il portiere vola sulla traiettoria e respinge la punizione.',{xg,shotOnTarget:true});return}
   add(minute+3,'shot_missed',side,taker,'La punizione supera la barriera ma finisce fuori dallo specchio.',{xg,shotOnTarget:false});
 };
 const resolveAttack=(us:boolean,minute:number,shotter:Starter|null,creator:Starter|null,contextBoost=0,context="l'azione",insideChance=.24)=>{
   const own=us?ps:oppPs,other=us?oppPs:ps,side=us?'user':'opp',outcome=rnd();
   if(outcome<.64){finish(us,minute,shotter,creator,contextBoost,context);return}
   if(outcome<.86){const defender=choose(other,'defender','D');add(minute,'duel',us?'opp':'user',defender,(defender?.player_name||"Il difensore")+' legge la giocata, chiude lo spazio e ferma l’azione prima del tiro.');return}
   const defender=choose(other,'defender','D'),inArea=rnd()<insideChance;
   add(minute,'foul',side,defender,(defender?.player_name||"Il difensore")+' arriva in ritardo sul portatore di palla e commette fallo.');
   if(inArea)penaltyChain(us,minute+1);else freeKickChain(us,minute+1);
 };
 const possessionChain=(us:boolean,minute:number)=>{
   const own=us?ps:oppPs;if(!own.length)return;const d=choose(own,'defender','D'),m1=choose(own,'creator','C'),m2=choose(own,'creator','C'),a=choose(own,'shot','A');
   add(minute,'possession',us?'user':'opp',d,(d?.player_name||sideName(us))+' apre la costruzione dal basso e aspetta che il pressing si muova.');
   add(minute,'possession',us?'user':'opp',m1,(m1?.player_name||"Il centrocampista")+' viene incontro, riceve tra le linee di pressione e gira il gioco con un tocco.');
   if(rnd()<.28){add(minute+1,'duel',us?'opp':'user',null,'La pressione avversaria arriva in tempo e forza una giocata sporca: il possesso cambia padrone.');return}
   add(minute+1,'action',us?'user':'opp',m2,(m2?.player_name||"Un altro centrocampista")+' trova spazio tra le linee e punta la zona centrale.');
   if(rnd()<clamp(.55+((style==='Possesso'&&us) ? .12 : 0)+((style==='Verticale'&&us) ? .05 : 0),.4,.75)){add(minute+1,'action',us?'user':'opp',a,(a?.player_name||"L'attaccante")+' viene incontro, appoggia di prima e poi attacca subito lo spazio alle spalle del centrale.');add(minute+2,'transition',us?'user':'opp',m2,(m2?.player_name||"Il centrocampista")+' legge il movimento, chiude l’uno-due e infila il pallone nello spazio.');add(minute+2,'action',us?'user':'opp',a,(a?.player_name||"L'attaccante")+' si inserisce alle spalle dei difensori e riceve in corsa, con la porta davanti.');resolveAttack(us,minute+3,a,m2,.035,"la manovra costruita",.24)}else add(minute+2,'possession',us?'user':'opp',m2,(m2?.player_name||"Il centrocampista")+' non trova il varco e preferisce ricominciare, mantenendo il possesso.');
 };
 const pressChain=(us:boolean,minute:number)=>{
   const own=us?ps:oppPs,other=us?oppPs:ps;if(!own.length)return;const presser=choose(own,'creator','C'),victim=choose(other,'defender','D'),att=choose(own,'shot','A');
   add(minute,'possession',us?'opp':'user',victim,(victim?.player_name||sideName(!us))+' riceve vicino alla propria area e prova a uscire palla al piede.');
   add(minute,'press',us?'user':'opp',presser,(presser?.player_name||sideName(us))+' accorcia forte e chiude la linea di passaggio.');
   if(rnd()<clamp(.48+((style==='Pressing'&&us) ? .18 : 0)+(quality(presser)-1)*.35,.32,.75)){add(minute,'transition',us?'user':'opp',presser,(presser?.player_name||"Il centrocampista")+' ruba palla in zona alta e serve immediatamente '+(att?.player_name||"l'attaccante")+' dentro l’area.');resolveAttack(us,minute+1,att,presser,.075,"il recupero alto",.30)}
   else{add(minute+1,'action',us?'opp':'user',victim,(victim?.player_name||sideName(!us))+' resiste alla pressione, protegge palla e trova l’uomo libero per uscire.');if(rnd()<.18)add(minute+1,'yellow',us?'user':'opp',presser,(presser?.player_name||"Il giocatore in pressione")+' arriva un attimo in ritardo nel tentativo di recuperare: fallo netto e cartellino giallo.')}
 };
 while(m<88){
   m+=3+Math.floor(rnd()*3);if(m>=90)break;if(m>43&&m<48)m=48;
   const trailing=usGoals<opGoals,leading=usGoals>opGoals,late=m>70,attackShare=usShare+(late&&trailing?.045:0)-(late&&leading?.02:0),us=rnd()<attackShare;
   const r=rnd(),mindAttack=us&&mentality==='attack',mindDefend=us&&mentality==='defend',counterChance=((style==='Contropiede'&&us) ? .34 : .20)+((style==='Verticale'&&us) ? .08 : 0)+(mindAttack ? .05 : 0),pressChance=((style==='Pressing'&&us) ? .27 : .15)+(mindAttack ? .05 : 0)-(mindDefend ? .04 : 0),possessionChance=((style==='Possesso'&&us) ? .38 : .25)+(mindDefend ? .08 : 0);
   if(r<counterChance)counterChain(us,m);
   else if(r<counterChance+pressChance)pressChain(us,m);
   else if(r<counterChance+pressChance+possessionChance)possessionChain(us,m);
   else{const own=us?ps:oppPs,other=us?oppPs:ps,creator=choose(own,'creator','C'),shotter=choose(own,'shot','A');add(m,'action',us?'user':'opp',creator,(creator?.player_name||sideName(us))+' riceve tra le linee, porta palla in avanti e cerca un compagno nell’ultimo terzo.');if(rnd()<.56)resolveAttack(us,m+1,shotter,creator,.015,"l'azione",.20);else{const defender=choose(other,'defender','D');add(m+1,'duel',us?'opp':'user',defender,(defender?.player_name||"Il difensore")+' legge l’ultimo passaggio, esce in anticipo e interrompe la giocata.');if(rnd()<.19)add(m+2,'yellow',us?'opp':'user',defender,(defender?.player_name||"Il difensore")+' trattiene l’avversario per evitare che riparta subito: l’arbitro estrae il cartellino giallo.')}}
   if(injuryCount<1&&rnd()<.006){const injurySide=rnd()<.64?'user':'opp',pool=injurySide==='user'?ps:oppPs,inj=pool.length?pool[Math.floor(rnd()*pool.length)]:null;if(inj){const sev=rnd(),weeks=sev<.20?0:sev<.90?(rnd()<.62?1:2):(rnd()<.5?3:4),label=weeks===0?"trauma lieve":weeks===1?"problema muscolare lieve":weeks===2?"lesione di media entità":weeks===3?"infortunio serio":"infortunio importante",detail=weeks===0?"Lo staff lo accompagna fuori per precauzione: potrebbe recuperare già per la prossima gara.":weeks===1?"Lo staff teme uno stop breve: la prossima partita è a forte rischio.":weeks===2?"Il gesto è doloroso: serviranno verosimilmente un paio di giornate di recupero.":"I segnali non sono buoni: si prospetta uno stop di diverse settimane.";add(m+2,'injury',injurySide,inj,inj.player_name+' si ferma dopo un contrasto e chiede subito il cambio. '+detail,{injuryWeeks:weeks,injuryLabel:label});injuryCount++}}
 }
 add(45,'phase','user',null,'INTERVALLO — il primo tempo entra nell’analisi dello staff.');
 out.sort((a,b)=>a.minute-b.minute);
 return out
}

export function buildPlayerStats(run:string,round:number,starters:Starter[],events:MatchEvent[]){const rnd=seeded(`${run}|g${round}|stats2`),oppGoals=events.filter(e=>e.side==='opp'&&e.type==='goal').length,oppShots=events.filter(e=>e.side==='opp'&&e.xg!=null);return starters.map(p=>{const pe=events.filter(e=>e.side==='user'&&e.player?.player_id===p.player_id),assists=events.filter(e=>e.side==='user'&&e.assist?.player_id===p.player_id&&e.type==='goal').length,shots=pe.filter(e=>e.xg!=null).length,sot=pe.filter(e=>e.xg!=null&&e.shotOnTarget).length,xg=pe.reduce((a,e)=>a+Number(e.xg||0),0),goals=pe.filter(e=>e.type==='goal').length,errors=pe.filter(e=>e.type==='error').length,yellows=pe.filter(e=>e.type==='yellow').length;if(p.role==='P'){const saves=events.filter(e=>e.type==='keeper_save'&&e.player?.player_id===p.player_id).length||Math.max(0,oppShots.filter(e=>e.shotOnTarget).length-oppGoals),rating=clamp(6+saves*.22+(oppGoals===0?.35:0)-oppGoals*.16-errors*.7,4.5,9.3);return{player_id:p.player_id,player_name:p.player_name,rating:+rating.toFixed(1),goals:0,chances:0,recoveries:0,duels:0,progressions:0,dangerous_errors:errors,saves,goals_conceded:oppGoals,interventions:saves+Math.round(rnd()*3),shots:0,shots_on_target:0,assists:0,xg:0,yellow_cards:yellows,fouls:yellows}}
 const rec=Math.round((p.role==='D'?6:p.role==='C'?5:2)+pe.filter(e=>e.type==='press').length*2+rnd()*2),duels=Math.round((p.role==='D'?6:p.role==='C'?4:2)+pe.filter(e=>e.type==='duel').length*2+rnd()*2),prog=Math.round((p.role==='C'?5:p.role==='A'?4:2)+pe.filter(e=>['transition','possession','action'].includes(e.type)).length*1.5+rnd()*2),activity=goals*1.05+assists*.65+sot*.18+rec*.03+duels*.025+prog*.035-errors*.7,rating=clamp(5.65+activity+(p.confidence-50)*.006+(rnd()-.5)*.3,4.5,9.4);return{player_id:p.player_id,player_name:p.player_name,rating:+rating.toFixed(1),goals,chances:shots,recoveries:rec,duels,progressions:prog,dangerous_errors:errors,saves:0,goals_conceded:0,interventions:0,shots,shots_on_target:sot,assists,xg:+xg.toFixed(3),yellow_cards:yellows,fouls:yellows}})}
export function matchSummary(events:MatchEvent[]){const side=(s:'user'|'opp')=>{const e=events.filter(x=>x.side===s),shots=e.filter(x=>x.xg!=null),goals=e.filter(x=>x.type==='goal').length;return{goals,shots:shots.length,onTarget:shots.filter(x=>x.shotOnTarget).length,xg:+shots.reduce((a,x)=>a+Number(x.xg||0),0).toFixed(2),corners:e.filter(x=>x.type==='setpiece').length,yellows:e.filter(x=>x.type==='yellow').length}};return{user:side('user'),opp:side('opp')}}