"use client";
import { ArrowLeft, Shield, Sparkles } from "lucide-react";
import Link from "next/link";
import { useEffect,useState } from "react";
import { createClient } from "@supabase/supabase-js";
const supabase=createClient("https://fqngllsmfqatgwzezuus.supabase.co","sb_publishable_JfPi6jdFfg8l51Z7SG3IYw_kK5J0x4L");
type P={player_id:string;player_name:string;role:string;source_club:string;confidence:number;matrix_rank:number};
export default function Rosa(){const [players,setPlayers]=useState<P[]>([]),[club,setClub]=useState(""),[loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{const id=new URLSearchParams(location.search).get("run");if(!id)return;const [r,p]=await Promise.all([supabase.from("game_runs").select("club_code").eq("id",id).single(),supabase.from("game_run_players").select("player_id,player_name,role,source_club,confidence,matrix_rank").eq("run_id",id).eq("squad_status","accepted").order("role")]);if(r.data)setClub(r.data.club_code);if(p.data)setPlayers(p.data);setLoading(false)})()},[]);
return <main className="squadPage"><div className="newTop"><Link href="/" className="back"><ArrowLeft size={17}/> Hub</Link><span className="matrixRun">{club} · ROSA INIZIALE</span></div><section className="squadHero"><p className="eyebrow">FASE 03 // LA TUA SQUADRA</p><h1>Questi sono i tuoi uomini.</h1><p>La Matrice ha deciso chi arriva. Adesso tocca a te capire cosa farne.</p></section>{loading?<p>Caricamento rosa…</p>:<div className="squadRoles">{["P","D","C","A"].map(role=><section className="squadRole" key={role}><div className="cardHead"><span>{role==="P"?"PORTIERI":role==="D"?"DIFENSORI":role==="C"?"CENTROCAMPISTI":"ATTACCANTI"}</span><b>{players.filter(p=>p.role===role).length}</b></div>{players.filter(p=>p.role===role).map(p=><div className="squadPlayer" key={p.player_id}><div className="miniAvatar">{p.player_name[0]}</div><div><strong>{p.player_name}</strong><span>{p.source_club} · Matrice #{p.matrix_rank}</span></div><div className="squadTrust"><small>FIDUCIA</small><b>{p.confidence}%</b></div></div>)}</section>)}</div>}<div className="squadNext"><Shield size={18}/><div><strong>16 giocatori. Nessuna scusa.</strong><span>Prossimo passo: scegliere modulo, gerarchie e primo undici.</span></div><button disabled><Sparkles size={16}/> PREPARA LA SQUADRA</button></div></main>}