"use client";
import {Shield,Sparkles,CalendarDays,Users,Activity,BarChart3,Crown,HeartHandshake,AlertTriangle,Layers3}from"lucide-react";
import brand90 from"../assets/logos/SidebarPNG.png";import rosaBg from"../assets/ambience/Rosa.jpeg";import{PLAYER_PHOTOS}from"../player-photos";import Link from"next/link";import{useEffect,useMemo,useState}from"react";import{createClient}from"@supabase/supabase-js";import{clubName}from"../lib/clubLogos";import{benchTolerance}from"../lib/psychologyEngine";
const supabase=createClient("https://fqngllsmfqatgwzezuus.supabase.co","sb_publishable_JfPi6jdFfg8l51Z7SG3IYw_kK5J0x4L");
const CLUB:any={ATA:"atalanta",BOL:"bologna",CAG:"cagliari",COM:"como",FIO:"fiorentina",FRO:"frosinone",GEN:"genoa",INT:"inter",JUV:"juventus",LAZ:"lazio",LEC:"lecce",MIL:"milan",MON:"monza",NAP:"napoli",PAR:"parma",ROM:"roma",SAS:"sassuolo",TOR:"torino",UDI:"udinese",VEN:"venezia"};
const FM:any={"a21d277e-cc82-46eb-840a-4310bf01b266":"fm_13227290__FADERA.png","47bec44d-c12e-4be5-a5f8-da6d800a4313":"fm_45111317__SUGAWARA.png","167283e8-1295-4e02-8b35-2c6c988050d3":"fm_83115694__ZÈ_PEDRO.png","4722d0a5-edac-4e5f-959e-bbf03a972c4a":"fm_2000312673__RODRIGUEZ.png","d7bd0748-37f6-4ead-b67c-a943c7f10154":"fm_2000128983__NJIE.png","f6405fd8-494a-456c-be7a-124566eda398":"fm_12080051__SARR.png","f1756a14-f96a-429b-9336-84f3ffa82543":"fm_62201068__ILIC.png","b469215a-2dec-4862-bca5-63c745b8bc3f":"fm_91167629__TOURÉ.png","0fe6c8f2-f860-47c2-a5bf-a7c7d74cc766":"fm_2000186695__ZIOLKOWSKI.png","cd7866b6-4ca9-4e6c-8665-df1582c1fd74":"fm_18111492__LEYSEN.png","0899f9bd-9fe0-4baf-b289-41b74d081f75":"fm_43036636__EL_SHAARAWY.png"};
type P={player_id:string;player_name:string;role:string;source_club:string;confidence:number;manager_trust:number;personality:string;squad_status_role:string;fitness:number;matrix_rank:number;availability?:string};
function SquadFace({p}:{p:P}){const[bad,setBad]=useState(false),src=PLAYER_PHOTOS[p.player_id]||face(p);return <span className="squadFaceWrap">{!bad?<img className="playerFace playerFaceLarge" src={src} onError={()=>setBad(true)} alt={p.player_name}/>:<i>{p.player_name.slice(0,2)}</i>}</span>}
function face(p:P){const dir=CLUB[p.source_club]||p.source_club.toLowerCase(),clean=p.player_name.toUpperCase().replace(/[^A-ZÀ-ÖØ-Ý0-9]+/g,"_").replace(/^_|_$/g,"");return "/assets/players/"+dir+"/"+(FM[p.player_id]||p.player_id+"__"+clean+".png")}
export default function Rosa(){
 const[players,setPlayers]=useState<P[]>([]),[club,setClub]=useState(""),[run,setRun]=useState(""),[loading,setLoading]=useState(true),[benchStreak,setBenchStreak]=useState<Record<string,number>>({});
 useEffect(()=>{(async()=>{const id=new URLSearchParams(location.search).get("run")||"";setRun(id);if(!id)return;const[r,p,u]=await Promise.all([
  supabase.from("game_runs").select("club_code,current_round").eq("id",id).single(),
  supabase.from("game_run_players").select("player_id,player_name,role,source_club,confidence,manager_trust,personality,squad_status_role,fitness,matrix_rank,availability").eq("run_id",id).eq("squad_status","accepted").order("role"),
  supabase.from("game_player_usage").select("player_id,round,started").eq("run_id",id).order("round",{ascending:false})
 ]);if(r.data)setClub(r.data.club_code);if(p.data)setPlayers((p.data||[]) as P[]);const bs:Record<string,number>={},seen=new Set<string>();for(const x of u.data||[]){if(seen.has(x.player_id))continue;if(x.started){seen.add(x.player_id);continue}bs[x.player_id]=(bs[x.player_id]||0)+1}setBenchStreak(bs);setLoading(false)})()},[]);
 const sorted=useMemo(()=>[...players].sort((a,b)=>(b.manager_trust+b.confidence)-(a.manager_trust+a.confidence)),[players]);
 const leader=sorted.find(p=>p.personality==="Leader")||sorted[0];
 const unhappy=players.filter(p=>(benchStreak[p.player_id]||0)>=benchTolerance(p.personality,p.squad_status_role)||p.confidence<35||p.manager_trust<35);
 const core=players.filter(p=>p.manager_trust>=65||p.personality==="Leader"||p.personality==="Uomo squadra").slice(0,6);
 const avgTrust=players.length?Math.round(players.reduce((a,p)=>a+(p.manager_trust||50),0)/players.length):0,avgConfidence=players.length?Math.round(players.reduce((a,p)=>a+p.confidence,0)/players.length):0;
 const dynamics=avgTrust>=65&&avgConfidence>=55?"GRUPPO COESO":unhappy.length>=4?"SPOGLIATOIO TESO":unhappy.length?"EQUILIBRIO FRAGILE":"GRUPPO STABILE";
 return <main className="seasonPage ambienceSection" style={{backgroundImage:`linear-gradient(rgba(4,12,9,.82),rgba(4,12,9,.95)),url(${rosaBg.src})`}}><aside className="seasonNav"><div className="seasonBrand"><img src={brand90.src} alt="90 MINUTES"/></div><b>STAGIONE</b><Link href={"/stagione?run="+run}><BarChart3/> Hub</Link><Link className="active" href={"/rosa?run="+run}><Users/> Rosa</Link><Link href={"/calendario?run="+run}><CalendarDays/> Calendario</Link><Link href={"/classifica?run="+run}><Activity/> Classifica</Link><Link href={"/statistiche-stagione?run="+run}><BarChart3/> Statistiche</Link><small>ARCHIVIO</small><span>Movimenti</span><span>Report</span></aside><section className="squadPage seasonSectionMain">
 <header className="squadHero squadHeroNew"><div><p className="eyebrow">ROSA // {clubName(club)}</p><h1>Spogliatoio.</h1><p>La Fiducia misura come il giocatore vive il proprio momento. Il Rapporto Mister misura quanto crede nelle tue scelte. Entrambi incidono sul rendimento in campo.</p></div><div className="squadCount"><strong>{players.length}</strong><span>GIOCATORI</span></div></header>
 {!loading&&<section className="dressingRoom"><div className="dressingHead"><div><small>DINAMICHE DI SQUADRA</small><h2>{dynamics}</h2></div><span>{unhappy.length} CASI DA GESTIRE</span></div><div className="dressingGrid">
  <article><Crown/><small>LEADER SPOGLIATOIO</small><strong>{leader?.player_name||"—"}</strong><p>{leader?leader.personality+" · "+leader.squad_status_role:"Nessuna gerarchia definita"}</p></article>
  <article><HeartHandshake/><small>CLIMA</small><strong>{avgTrust}%</strong><p>Rapporto medio con il mister · Fiducia media {avgConfidence}%</p></article>
  <article><Layers3/><small>NUCLEO GUIDA</small><strong>{core.length}</strong><p>{core.map(p=>p.player_name).slice(0,3).join(" · ")||"In formazione"}</p></article>
  <article className={unhappy.length?"warning":""}><AlertTriangle/><small>SCONTENTI / FRAGILI</small><strong>{unhappy.length}</strong><p>{unhappy.slice(0,3).map(p=>p.player_name).join(" · ")||"Nessun segnale critico"}</p></article>
 </div>{unhappy.length>0&&<div className="dynamicsList">{unhappy.map(p=><div key={p.player_id}><b>{p.player_name}</b><span>{(benchStreak[p.player_id]||0)>=benchTolerance(p.personality,p.squad_status_role)?`${benchStreak[p.player_id]} gare senza partire titolare`:p.manager_trust<35?"Rapporto con il mister deteriorato":"Fiducia personale bassa"}</span><em>{p.personality} · {p.squad_status_role}</em></div>)}</div>}</section>}
 {loading?<p className="squadLoading">Caricamento rosa…</p>:<div className="squadRoles squadRolesBoard">{["P","D","C","A"].map(role=><section className="squadRole" key={role}><div className="squadRoleHead"><div><small>{role}</small><strong>{role==="P"?"PORTIERI":role==="D"?"DIFENSORI":role==="C"?"CENTROCAMPISTI":"ATTACCANTI"}</strong></div><b>{players.filter(p=>p.role===role).length}</b></div><div className="squadRolePlayers">{players.filter(p=>p.role===role).map(p=><article className={"squadPlayerCard psychology "+(unhappy.some(x=>x.player_id===p.player_id)?"needsCare ":"")+(String(p.availability||"").startsWith("injured_until:")?"isInjured":"")} key={p.player_id}><SquadFace p={p}/><div className="squadPlayerInfo"><strong>{p.player_name}</strong><span>{clubName(p.source_club)} · {p.squad_status_role}</span><small>{String(p.availability||"").startsWith("injured_until:")?"INFORTUNATO · "+p.fitness+"% FIT":(p.personality||"Profilo neutro")+" · "+p.fitness+"% FIT · MATRICE #"+p.matrix_rank}</small></div><div className="squadMind"><div><small>FIDUCIA</small><b>{p.confidence}%</b><i><span style={{width:p.confidence+"%"}}/></i></div><div><small>FORMA</small><b>{p.fitness}%</b><i><span style={{width:p.fitness+"%"}}/></i></div></div></article>)}</div></section>)}</div>}
 <div className="squadNext"><Shield size={18}/><div><strong>Psicologia e gerarchie incidono sulla partita.</strong><span>Fiducia e rapporto con il mister entrano ora nel rendimento del motore partita.</span></div><Link className="squadPrepare" href={"/prepara?run="+run}><Sparkles size={16}/> PREPARA LA SQUADRA</Link></div>
 </section></main>
}
