"use client";
import brandWordmark from"./assets/logos/Full horizontal 90 MINUTES wordmark.jpg";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CalendarDays,ChevronRight,ClipboardList,HeartPulse,LayoutDashboard,MessageSquareText,Shield,Sparkles,Trophy,UsersRound,UserRoundCog} from "lucide-react";
import {createClient} from "@supabase/supabase-js";
import {PLAYER_PHOTOS} from "./player-photos";
const sb=createClient("https://fqngllsmfqatgwzezuus.supabase.co","sb_publishable_JfPi6jdFfg8l51Z7SG3IYw_kK5J0x4L");
type P={player_id:string;player_name:string;role:string;confidence:number;source_club:string};
function Face({p}:{p:P}){return <div className="homeFace">{PLAYER_PHOTOS[p.player_id]?<img src={PLAYER_PHOTOS[p.player_id]} alt={p.player_name}/>:<span>{p.player_name.slice(0,2)}</span>}</div>}
export default function Home(){
 const[run,setRun]=useState(""),[club,setClub]=useState(""),[round,setRound]=useState(0),[pts,setPts]=useState(0),[players,setPlayers]=useState<P[]>([]),[opp,setOpp]=useState("—"),[matches,setMatches]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const rs=await sb.from("game_runs").select("id,club_code,current_round,squad_size,status").order("current_round",{ascending:false}).order("created_at",{ascending:false}).limit(20);const r=(rs.data||[]).find((x:any)=>(x.squad_size||0)>=16&&x.status!=="finished")||rs.data?.[0];if(!r)return;setRun(r.id);setClub(r.club_code);setRound(r.current_round||0);
 const [pp,mm,fx]=await Promise.all([sb.from("game_run_players").select("player_id,player_name,role,confidence,source_club").eq("run_id",r.id).eq("squad_status","accepted"),sb.from("game_matches").select("round,opponent_code,user_goals,opponent_goals,status").eq("run_id",r.id).eq("status","finished").order("round",{ascending:false}).limit(5),sb.from("game_schedule").select("home_code,away_code").eq("run_id",r.id).eq("round",(r.current_round||0)+1).or(`home_code.eq.${r.club_code},away_code.eq.${r.club_code}`).maybeSingle()]);
 setPlayers((pp.data||[]) as P[]);setMatches(mm.data||[]);setPts((mm.data||[]).reduce((a:number,m:any)=>a+(m.user_goals>m.opponent_goals?3:m.user_goals===m.opponent_goals?1:0),0));if(fx.data)setOpp(fx.data.home_code===r.club_code?fx.data.away_code:fx.data.home_code)})()},[]);
 const sorted=useMemo(()=>[...players].sort((a,b)=>b.confidence-a.confidence),[players]),hot=sorted.slice(0,3),crisis=[...sorted].reverse().slice(0,3),avg=players.length?Math.round(players.reduce((a,p)=>a+p.confidence,0)/players.length):0;
 return <main className="shell homeHub"><aside className="sidebar"><div className="brand brand90"><img className="brand90Logo" src={brandWordmark.src} alt="90 MINUTES"/></div><nav><a className="active"><LayoutDashboard size={18}/>Hub</a><Link href={run?"/rosa?run="+run:"/rosa"}><UsersRound size={18}/>Rosa</Link><Link href={run?"/prepara?run="+run:"/prepara"}><Shield size={18}/>Formazione</Link><Link href={run?"/matrice?run="+run:"/matrice"}><Sparkles size={18}/>Matrice</Link><Link href={run?"/classifica?run="+run:"/classifica"}><Trophy size={18}/>Campionato</Link><Link href={run?"/stagione?run="+run:"/stagione"}><BarChart3 size={18}/>Statistiche</Link><Link href={run?"/vigilia?run="+run:"/vigilia"}><ClipboardList size={18}/>Match Analyst</Link></nav><Link href="/nuova-partita" className="newRunLink"><Sparkles size={15}/> Nuova partita</Link><div className="sidebarBottom"><span>RUN ATTIVA</span><strong>{club||"—"}</strong><small>Giornata {round+1}</small></div></aside>
 <section className="content"><header><div><p className="eyebrow">CENTRO SPORTIVO // HUB STAGIONE</p><h1>Buon pomeriggio, Mister.</h1><p className="muted">Qui non avanza il tempo: leggi squadra, persone e prossima partita prima di decidere.</p></div></header><div className="dashboard">
 <section className="card nextMatch"><div className="cardHead"><span>PROSSIMA PARTITA</span><span className="pill">SERIE A · G{round+1}</span></div><div className="match"><div className="club"><div className="crest">{club.slice(0,2)}</div><strong>{club}</strong><span>{pts} pt*</span></div><div className="versus"><small>PROSSIMA GIORNATA</small><b>VS</b><span>Preparazione richiesta</span></div><div className="club"><div className="crest away">{opp.slice(0,2)}</div><strong>{opp}</strong><span>Avversario</span></div></div><div className="matchActions"><Link className="primary" href={"/prepara?run="+run}>Prepara la partita <ChevronRight size={17}/></Link><Link className="secondary" href={"/vigilia?run="+run}>Rapporto avversario</Link></div></section>
 <section className="card staffCard"><div className="cardHead"><span>STAFF TECNICO</span><UserRoundCog size={17}/></div><div className="staffMember"><div className="staffIcon">V</div><div><strong>Allenatore in seconda</strong><span>Tattica · sostituzioni · lettura dell'intervallo</span></div></div><div className="staffMember"><div className="staffIcon">MA</div><div><strong>Match Analyst</strong><span>Profilo avversario · spazi · rischi del piano gara</span></div></div><div className="staffMember"><div className="staffIcon">PM</div><div><strong>Player Manager</strong><span>Fiducia · gerarchie · promesse · malumori</span></div></div><p className="staffNote">Lo staff suggerisce problemi e opzioni: la decisione resta tua.</p></section>
 <section className="card peopleCard"><div className="cardHead"><span>PROTAGONISTI</span><HeartPulse size={17}/></div><div className="faceCards">{hot.map(p=><div className="faceStat" key={p.player_id}><Face p={p}/><div><strong>{p.player_name}</strong><span>{p.role} · {p.source_club}</span><b>{p.confidence}% <em>FIDUCIA</em></b></div></div>)}</div></section>
 <section className="card peopleCard crisisCard"><div className="cardHead"><span>DA SEGUIRE</span><span className="pill warning">FIDUCIA</span></div><div className="faceCards">{crisis.map(p=><div className="faceStat" key={p.player_id}><Face p={p}/><div><strong>{p.player_name}</strong><span>{p.role} · attenzione psicologica</span><b>{p.confidence}% <em>{p.confidence<40?"IN CRISI":"FRAGILE"}</em></b></div></div>)}</div></section>
 <section className="card confidence"><div className="cardHead"><span>FIDUCIA SQUADRA</span><span className="score">{avg}</span></div><div className="confidenceList">{sorted.slice(0,6).map(p=><div className="player" key={p.player_id}><Face p={p}/><div className="playerName"><strong>{p.player_name}</strong><span>{p.role}</span></div><div className="meter"><i style={{width:p.confidence+"%"}}/></div><b>{p.confidence}%</b></div>)}</div><Link className="textButton" href={"/rosa?run="+run}>Vedi rosa e gerarchie <ChevronRight size={16}/></Link></section>
 <section className="card results"><div className="cardHead"><span>ULTIME PARTITE</span><CalendarDays size={17}/></div>{matches.map(m=><div className="result" key={m.round}><span className={"resultBadge "+(m.user_goals>m.opponent_goals?"win":m.user_goals<m.opponent_goals?"loss":"")}>{m.user_goals>m.opponent_goals?"V":m.user_goals<m.opponent_goals?"P":"N"}</span><strong>{m.opponent_code}</strong><b>{m.user_goals}–{m.opponent_goals}</b></div>)}{!matches.length&&<p className="muted">Nessuna partita salvata nella run.</p>}</section>
 </div><footer><span>90 MINUTES // CLUB OS</span><span>Peschi giocatori. Costruisci una squadra. Gestisci persone.</span></footer></section></main>
}