"use client";
import"./staff.css";import Link from"next/link";import{useEffect,useMemo,useState}from"react";import{Users,Shield,Brain,HeartPulse,Dumbbell,Handshake,Star,AlertTriangle,BarChart3}from"lucide-react";import{createClient}from"@supabase/supabase-js";import brand90 from"../assets/logos/SidebarPNG.png";
const sb=createClient("https://fqngllsmfqatgwzezuus.supabase.co","sb_publishable_JfPi6jdFfg8l51Z7SG3IYw_kK5J0x4L");
const CANDIDATES=[
 {key:"vice_stabile",role:"vice",name:"Marco Bellini",level:3,cost:16,loyalty:88,ambition:36,reputation:54,specialty:"Gestione del gruppo",release:8},
 {key:"vice_elite",role:"vice",name:"Luca Ferretti",level:5,cost:29,loyalty:48,ambition:91,reputation:86,specialty:"Lettura live",release:18},
 {key:"analyst_data",role:"analyst",name:"Davide Serra",level:4,cost:22,loyalty:72,ambition:63,reputation:72,specialty:"Analisi avversario",release:12},
 {key:"analyst_top",role:"analyst",name:"Tommaso Riva",level:5,cost:31,loyalty:44,ambition:94,reputation:90,specialty:"Tattica avanzata",release:20},
 {key:"fitness_safe",role:"fitness",name:"Paolo Moretti",level:3,cost:15,loyalty:90,ambition:28,reputation:50,specialty:"Recupero",release:7},
 {key:"fitness_elite",role:"fitness",name:"Andrea Bassi",level:5,cost:28,loyalty:57,ambition:82,reputation:82,specialty:"Carichi e performance",release:17},
 {key:"physio_safe",role:"physio",name:"Sara Conti",level:4,cost:20,loyalty:86,ambition:44,reputation:66,specialty:"Prevenzione",release:10},
 {key:"physio_star",role:"physio",name:"Elena Marini",level:5,cost:30,loyalty:51,ambition:88,reputation:88,specialty:"Recupero rapido",release:19},
 {key:"ds_network",role:"ds",name:"Riccardo Fontana",level:4,cost:23,loyalty:74,ambition:67,reputation:76,specialty:"Negoziazione",release:13},
 {key:"ds_elite",role:"ds",name:"Matteo Leone",level:5,cost:32,loyalty:46,ambition:96,reputation:93,specialty:"Network mercato",release:22}
];
const ROLE_LABEL:any={vice:"ALLENATORE IN SECONDA",analyst:"MATCH ANALYST",fitness:"PREPARATORE ATLETICO",physio:"FISIOTERAPISTA",ds:"DIRETTORE SPORTIVO"};
const ROLE_ICON:any={vice:Users,analyst:Brain,fitness:Dumbbell,physio:HeartPulse,ds:Handshake};
export default function StaffMarket(){const[run,setRun]=useState(""),[budget,setBudget]=useState(100),[spent,setSpent]=useState(0),[staff,setStaff]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
useEffect(()=>{(async()=>{const q=new URLSearchParams(location.search),id=q.get("run")||Object.keys(localStorage).filter(k=>k.startsWith("fm_run_")).map(k=>localStorage.getItem(k)).find(Boolean)||"";setRun(id);if(!id)return;await sb.from("game_staff_budget").upsert({run_id:id},{onConflict:"run_id",ignoreDuplicates:true});const[b,s]=await Promise.all([sb.from("game_staff_budget").select("budget_total,budget_spent").eq("run_id",id).single(),sb.from("game_run_staff").select("*").eq("run_id",id)]);setBudget(b.data?.budget_total||100);setSpent(b.data?.budget_spent||0);setStaff(s.data||[])})()},[]);
const remaining=budget-spent,current=useMemo(()=>new Map(staff.map(x=>[x.staff_role,x])),[staff]);
async function hire(c:any){if(!run||busy)return;if(c.cost>remaining){setMsg("Budget staff insufficiente.");return}setBusy(true);setMsg("");const old=current.get(c.role),nextSpent=spent-(old?.cost||0)+c.cost;if(nextSpent>budget){setBusy(false);setMsg("Budget staff insufficiente.");return}const risk=Math.max(0,Math.min(100,Math.round(c.ambition*.55+c.reputation*.25-c.loyalty*.45)));const row={run_id:run,staff_role:c.role,staff_key:c.key,staff_name:c.name,level:c.level,specialty:c.specialty,cost:c.cost,hired_round:0,loyalty:c.loyalty,ambition:c.ambition,reputation:c.reputation,contract_until_round:38,release_cost:c.release,poach_risk:risk,updated_at:new Date().toISOString()};const r=await sb.from("game_run_staff").upsert(row,{onConflict:"run_id,staff_role"});if(r.error)setMsg(r.error.message);else{await sb.from("game_staff_budget").update({budget_spent:nextSpent,updated_at:new Date().toISOString()}).eq("run_id",run);setStaff(xs=>[...xs.filter(x=>x.staff_role!==c.role),row]);setSpent(nextSpent);setMsg(`${c.name} entra nello staff.`)}setBusy(false)}
return <main className="seasonPage"><aside className="seasonNav"><div className="seasonBrand"><img src={brand90.src} alt="90 MINUTES"/></div><b>STAGIONE</b><Link href={"/stagione?run="+run}><BarChart3/> Hub</Link><Link className="active" href={"/staff?run="+run}><Users/> Staff</Link><Link href={"/rosa?run="+run}><Shield/> Spogliatoio</Link></aside><section className="seasonSectionMain staffMarketPage"><header className="seasonPageHero"><div><p className="eyebrow">AREA TECNICA // MERCATO STAFF</p><h1>Costruisci lo staff.</h1><p>Competenza, costo e lealtà contano insieme. I profili migliori producono vantaggi più forti, ma i più ambiziosi possono attirare offerte da altri club.</p></div><div className="seasonHeroStat"><strong>{remaining}</strong><span>BUDGET RESIDUO</span></div></header>{msg&&<div className="tradeNotice good">{msg}</div>}<div className="staffMarketGrid">{["vice","analyst","fitness","physio","ds"].map(role=><section className="staffMarketRole" key={role}><div className="staffMarketRoleHead"><span>{ROLE_LABEL[role]}</span>{current.get(role)&&<b>ATTUALE · LV {current.get(role).level}</b>}</div>{CANDIDATES.filter(c=>c.role===role).map(c=>{const Icon=ROLE_ICON[role],risk=Math.max(0,Math.min(100,Math.round(c.ambition*.55+c.reputation*.25-c.loyalty*.45))),active=current.get(role)?.staff_key===c.key;return <article className={"staffCandidate "+(active?"active":"")} key={c.key}><div className="staffCandidateTop"><Icon/><div><small>{ROLE_LABEL[role]}</small><h3>{c.name}</h3></div><strong>LV {c.level}</strong></div><p>{c.specialty}</p><div className="staffCandidateStats"><span><Star/> QUALITÀ <b>{c.level}/5</b></span><span>LEALTÀ <b>{c.loyalty}</b></span><span>AMBIZIONE <b>{c.ambition}</b></span><span className={risk>=55?"risk":""}><AlertTriangle/> RISCHIO OFFERTA <b>{risk}%</b></span></div><div className="staffCandidateFoot"><span>COSTO <b>{c.cost}</b></span><span>CLAUSOLA <b>{c.release}</b></span><button disabled={busy||active} onClick={()=>hire(c)}>{active?"IN CARICA":"INGAGGIA"}</button></div></article>})}</section>)}</div></section></main>}
